### ISSUE TITLE
Ensure that there is an error when no report group is defined

### ISSUE THREAD

**Issue by zachary-foster** [nf-core/pathogensurveillance#21]
If no intelligible error is given:

```[tasklist]
### Tasks
- [x] Add to required column on line 194 in `bin/check_samplesheet.py` .
- [x] modify `bin/check_samplesheet.py` to check for this column and give an error if empty.
- [x] Add new check to `validate_and_transform` on line 63
```
