### ISSUE TITLE
README enhancements 

### ISSUE THREAD

**Issue by zachary-foster** [nf-core/pathogensurveillance#64]
```[tasklist]
### Tasks
- [ ] A more simplified introduction section called just "Introduction" .
- [ ] A bioinformatics-focused introduction for researchers, something like "Introduction for researchers/bioinformaticians".
- [ ] An in-depth tutorial with more explanation and in the context of a biological question. 
- [ ] An example report made from the tutorial dataset
- [ ] Explanation of output format (report, output directory)
- [ ] How to run Sequera Platform (which includes how to set up Google cloud, Azure, **AWS**, etc) 
- [ ] A list of all analyses done by the pipeline
- [ ] Benchmarking/Performance section with example profiles
- [ ] link to change log 
```
